pipeline {
    agent any

    stages {
        stage('Workspace setup') {
            steps {
                cleanWs()
                echo 'Workspace is cleaned'
                checkout scm
            }
        }
        stage('Build'){
            steps{
                dir('JiraPOM'){
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage ('Login Tests'){
            parallel{
                    stage('Chrome') {
                        steps{
                            dir('JiraPOM') {
                                sh 'mvn test -Dtest="LoginPageTest" -Dusername=automation40 -Dpassword=CCAutoTest19. -DbrowserType=chrome -DisRemote=true'
                                }
                            }
                    }
                    stage('Firefox'){
                        steps{
                            dir('JiraPOM') {
                                sh 'mvn test -Dtest="LoginPageTest" -Dusername=automation40 -Dpassword=CCAutoTest19. -DbrowserType=firefox -DisRemote=true'
                                }
                        }
                    }
                }
            }
        stage('Workspace teardown'){
            steps {
                cleanWs()
                echo 'Workspace is cleaned'
            }
        }
        }
    }