pipeline {
    agent any

    stages {
        stage('Workspace setup') {
            steps {
                cleanWs()
                echo 'Workspace is cleaned'
                checkout scm
            }
        }
        stage('Build'){
            steps{
                dir('JiraPOM'){
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage ('LoginPageTest'){
            parallel{
                    stage('Login') {
                        steps{
                                dir('JiraPOM') {
                                sh 'mvn test -Dtest="LoginPageTest" -Dusername=automation40 -Dpassword=CCAutoTest19. -DbrowserType=chrome -DisRemote=true'
                                }
                            }
                    }
                    stage('Paralell 2'){
                        steps{
                            echo 'Stage 2 - Paralell 2'

                        }
                    }
                }
            }
        stage('Workspace teardown'){
            steps {
                cleanWs()
                echo 'Workspace is cleaned'
            }
        }
        }
    }